### ISSUE TITLE
Bad en_GB.po

### ISSUE THREAD

**Issue by JassMan23** [ernesst/ActivityTracker#27]
The English translation seems to have been overwritten with Spanish? It is certainly not readable as English.

**Comment by mymike00** [comment]
yes, this [commit](https://github.com/ernesst/ActivityTracker/commit/50daca2bb0630dab99d1af370988dc492ecef57f) introduced it. I will revert it now but since everyone can translate this app errors like this one may happen again in the future.

I could enable an option s.t. translations need to be upvoted by other people before they gets into the app, but since there aren't lots of users I preferred to leave translation free to everyone. I will consider enabling that feature if this will happen more frequently

**Comment by JassMan23** [comment]
Easiest solution is just to set that all MRs require approval

**Comment by mymike00** [comment]
I merge translations from `weblate` branch to `master` manually but I can't check manually all the translations if are right or not... I don't speak so many languages :P

**Comment by JassMan23** [comment]
Moi non plus. All's well that ends well.
