### ISSUE TITLE
[feature request] add option to pause recording

### ISSUE THREAD

**Issue by Danfro** [ernesst/ActivityTracker#46]
Currently there is no way to pause a recording. It does either run or is stopped and saved. 

Sometimes one may want to pause recording. Say you are jogging along, meet a friend and have a chat. That would mess up your readings.

**Comment by mymike00** [comment]
Yeah, that would be useful indeed. Do you think something special for this needs to be written in the gpx? Because you don't want that time to end up in the activity effective time.
Also, do you have a suggestion on how to implement this in the UI? One way could be change the stop button in a pause one that opens a popup with 2 buttons: resume, that closes the popup and continues to track position, and stop, which shows the popup that is presented now with the stop button (confirmation for stopping). But idk if this adds too many taps to just end the activity...
Also, given that during activity the screeen is always on, my fear is that the activity can be paused accidentally (that is why there is a confirmation popup to stop it)

**Comment by Danfro** [comment]
This issue has been fixed with the app that is now developed under https://github.com/Danfro/ActivityTracker.
